---
header-includes:
  - \usepackage{lscape}
  - \newcommand{\blscape}{\begin{landscape}}
  - \newcommand{\elscape}{\end{landscape}}
output: 
  pdf_document:
fontsize: 12pt
geometry: margin=1in
documentclass: article
bibliography: NantucketMS.bib
csl: ecology.csl
---

# Appendix 2. Covariate details

We evaluated biophysical covariates (Table 2.1) expected to influence the distribution, abundance, and movements of sea ducks or, more likely, the distribution and availability of their benthic prey (e.g., mollusks and crustaceans); we did not have information related directly to the distribution of preferred prey. *Biophysical covariates could be characterized as strictly spatial or temporal effects (i.e., varying only among segments or within or among winters, respectively) or as spatiotemporal effects (i.e., varying among segments and within or among winters).* **BH: The previous sentence is hard to understand. I first understood it when I had a look at the table. Perhaps we can either reference the table or add examples?** We allowed the effect of bathymetry and relative sea surface temperature to vary over time within a given winter via interactions with day of season.  We also included a survey effort covariate and covariates that were solely a function of segment geographic location, which we used to address potential spatial correlation in the data.  We standardized (i.e., mean centered and scaled) all continuous covariates.  Appendix 3 describes and illustrates the use of an R function to visualize the spatial and temporal distribution of these covariates in Nantucket Sound.

\newpage
\blscape

**Table 2.1** Biophysical and survey covariates used to evaluate the distribution and abundance of Common Eider, Black, Surf, and White-winged Scoter, and Long-tailed Duck in Nantucket Sound during winters 2003 - 2005. ~~Variable type indicates whether an effect was spatial (S), temporal (T), or spatiotemporal (ST) during the study period (see Covariates section of text).~~ **This is a duplicate of footnote 1. We should remove either one.**

---------------------------------------------------------------------------------------------------------------------------
Variable                              Units     Variable  Description
(abbreviation)                                  type^1^              
---------------------------------- ----------- ---------- -----------------------------------------------------------------
Day of year (*time*)                   day         T      seasonality; number of days from 31 December; negative values	
                                                          indicate days prior to 31 December
                                                      
&nbsp;

Bathymetry (*depth*)                    m          S      bottom depth relative to mean high water; National Oceanic and 
                                                          Atmospheric Administration's (NOAA) National Geographic Data 
                                                          Center (NGDC): http://ngdc.noaa.gov/dem/squareCellGrid/download/385
                                                          [@Eakins2009]
                                           
&nbsp;

Sediment grain size (*meanphi*)        phi         S      sediment grain size (phi scale); @Poti2012 

&nbsp;

Sea floor surface area:                N/A         S      ratio of sea floor surface area [calculated from bathymetry;  
planimetric area (*SAR*)                                  @Jenness2004] to planimetric area; estimate of the topographic 
**Change label? See manuscript.**                         variability of the sea floor

&nbsp;

Epibenthic tidal velocity              m/s         S      average epibenthic tidal velocity during 2003-2005 based on monthly 
(mean; *tidebmean*)                                       Finite-Volume Community Ocean Model (FVCOM) data [structured grids from 
                                                          http://fvcom.smast.umassd.edu/Data/FVCOM/NECOFS/Archive/; @Chen2003; 
                                                          @Chen2011]

&nbsp;

Epibenthic tidal velocity              m/s	       S	    standard deviation of epibenthic tidal velocity during 2003-2005 base 
(standard deviation; *tidesd*)			                      based on monthly FVCOM structured grids [@Chen2003; @Chen2011]

&nbsp;                              

Water column stratification         *h*/*u^3^*     S	  potential for seasonal thermal stratification of the water column, 
potential (*strat*)			                              calculated ~~[@Simpson1974]~~ **BH: Strange place for reference** as the ratio of depth (*h*; from bathymetry) to 
                                                          the third power of surface tidal velocity [*u*; from monthly FVCOM 
                                                          structured grids; @Chen2003; @Chen2011] **BH: is *u* tidebmean?**; we report log~10~(*h*/*u^3^*) for 
                                                          each segment.  Higher values indicate areas more prone to thermal 
                                                          stratification during the summer.  Although the numerical value of 
                                                          log~10~(*h*/*u^3^*) at which stratification occurs depends on the choice of
                                                          *u*, relative values among locations remain consistent [@Simpson2012]
                                                          **BH: *h*/*u^3^* is not a unit!!**

&nbsp;                              

Chlorophyll-a (*chla*)               mg/m^3^	     S	    geometric mean of monthly composite chlorophyll-a levels from July 2002 
                                                          (first available) to March 2006; data from the Aqua MODIS satellite via 
                                                          NOAA Environmental Research Division's Data Access Program (ERDDAP): 
                                                          http://coastwatch.pfeg.noaa.gov/erddap/info/erdMEchlamday/index.html

&nbsp;                              

Chromophoric dissolved	              N/A	         S	    geometric mean of monthly composite chromophoric dissolved organic 
organic material (*cdom*)			                            material levels (measured based on absorbance values) from July 2002 (first
                                                          available) to March 2006; data from the Aqua MODIS satellite via NOAA ERDDAP:
                                                          http://coastwatch.pfeg.noaa.gov/erddap/info/erdMEcdommday/index.html.  No units
                                                          (absorbancy measure).  Note the experimental nature of this product.

&nbsp;                              

Sea bottom temperature (*SBT*)      	^o^C	      ST	    sea bottom (epibenthic) temperature averaged from May to October for each 
                                                          year (2003-2005) from monthly FVCOM structured grids [@Chen2003; @Chen2011].  
                                                          May through October corresponds to the period of settling of relevant bivalve 
                                                          spawn in the area [@Evans2011], and temperature potentially influences mussel
                                                          settling and growth [@Fay1983; @Newell1989]

&nbsp;                                                                                        

Sea surface temperature	              ^o^C	      ST	    monthly sea surface temperature from monthly FVCOM structured grid [@Chen2003;
(monthly; *SST~m~*)			                                  @Chen2011]; available alternative sea surface temperature sources possessed 
                                                          too coarse resolution [e.g., AHVRR Pathfinder; @Zipkin2010] or inconsistent
                                                          measurements in the study area [e.g., Aqua MODIS; @Winiarski2013]

&nbsp;

Sea surface temperature               ^o^C	      ST	    average seasonal (November through March) sea surface temperature from monthly
(Nov - Mar; *SST~w~*)			                                FVCOM structured grids [@Chen2003; @Chen2011] **BH: What does the ~w~ stand for? Winter? Explain.**

&nbsp;

Sea surface temperature               ^o^C        ST	    difference between the monthly sea surface temperature of a segment and the
(relative; *SST~rel~*)                                    average sea surface temperature of the entire study area; based on monthly 
                                                          FVCOM structured grids [@Chen2003; @Chen2011]
                                                          
&nbsp;

North Atlantic Oscillation            N/A          T      winter (December through March) North Atlantic Oscillation index based on
(Dec - Mar; *NAO~w~*)			                                the principal component time series of the leading empirical orthogonal 
                                                          function of sea level pressure anomalies over the Atlantic sector 
                                                          [@Hurrell1995; @Hurrell2010]; data from the Climate Analysis Section, 
                                                          National Center for Atmospheric Research: 
                                                          https://climatedataguide.ucar.edu/climate-data/hurrell-north-atlantic-oscillation-nao-index-pc-based 
                                                          (accessed 14 April 2014)

&nbsp;

Distance to land (*d2land*)           km           S	    distance to the nearest location of zero depth (from bathymetry)

&nbsp;

Ferry route within 1 km 	            N/A	         S      indicator of whether the ferry route from Cape Cod to Nantucket (Massachusetts
(*ferry*)                                                 Department of Transportation, Office of Transportation Planning) intersects
                                                          a given segment; the ferry route was buffered by 1 km to accommodate potential 
                                                          sea duck responses to ship traffic at a distance and uncertainty in ferry route 
                                                          [@Larsen2005; @DeLaCruz2014].  Ferries traversed this route approximately 16                                                  
                                                          times per day during the study period
                                                         
&nbsp;

Winter 2004 (*y2004*)                 N/A	         T	    indicator comparing surveys occurring from November 2004 through April 2005 
                                                          with those occurring from December 2003 through April 2004
                                                         
&nbsp;

Winter 2005 (*y2005*)                 N/A          T      indicator comparing surveys occurring from October 2005 through March 2006 
                                                          with those occurring from December 2003 through April 2004

&nbsp;

Easting (*xkm*)	                      km           S	    distance between the easting of a segment center from the median easting of 
                                                          all segments surveyed in the study area; negative and positive values indicate
                                                          segments west and east of the median easting, respectively

&nbsp;

Northing (*ykm*)                      km           S	    distance between the northing of a segment center from the median northing of 
                                                          all segments surveyed in the study area; negative and positive values indicate
                                                          segments south and north of the median northing, respectively

&nbsp;

Survey effort (*obs_window*)         km^2^	      ST      area of strip transect surveyed in a given segment on a given survey date;
                                                          calculated as the product of the length and width of the strip transect
                                                         
-----------------------------------------------------------------------------------------------------------------------
^1^Variable type: S (spatial; varying only among segments); T (temporal; varying only over time); ST (spatiotemporal; varying in space and time)
\elscape

## Literature cited
